name: "💡 Feature Request"
description: Create a new feature request
title: "💡 [REQUEST] - <title>"
labels: [
  "enhancement"
]
body:
  - type: textarea
    id: implementation_pr
    attributes:
      label: "Implementation PR"
      description: If you have a PR that implements this feature list it below
      placeholder: "#PullRequestID"
    validations:
      required: false
  - type: textarea
    id: reference_issues
    attributes:
      label: "Reference Issue(s)"
      description: List the issue(s) that are related to this feature request
      placeholder: "Closes #IssueID"
    validations:
      required: false
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide a brief explanation of the feature
      placeholder: Describe in a few lines your feature request
    validations:
      required: true
  - type: textarea
    id: unresolved_question
    attributes:
      label: "Unresolved questions"
      description: What questions still remain unresolved ?
      placeholder: Identify any unresolved issues.
    validations:
      required: false