name: "⚠️ Security Vulnerability Report"
description: File a security vulnerability report
title: "⚠️ [Security] - <title> "
labels: ["security"]
assignees:
  - pi0neerpat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this security vulnerability report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: e.g., email@example.com
    validations:
      required: true
  - type: textarea
    id: whats-wrong
    attributes:
      label: Describe the vulnerability
      description: A clear and concise description of what the vulnerability is.
      placeholder: What's wrong?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: |
        ![DESCRIPTION](LINK.png)
    validations:
      required: false
  - type: dropdown
    id: devices-affected
    attributes:
      label: What devices does this affect?
      multiple: true
      options:
        - All
        - Windows
        - macOS
        - Linux
        - Android
        - iOS
        - Other
  - type: dropdown
    id: browsers-affected
    attributes:
      label: What browsers does this affect?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other